# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
ifeq ($(CONFIG_OPLUS_CHARGER_MTK6983S),y)
obj-$(CONFIG_OPLUS_CHARGER)	+= oplus/
endif
ifeq ($(CONFIG_OPLUS_CHARGER_MTK6895S),y)
obj-$(CONFIG_OPLUS_CHARGER)	+= oplus_6895/
endif

